const ncaabbTeams = {
  "Southern California Trojans": "USC",
  "USC Trojans": "USC",
  "Austin Peay Governors": "PEAY",
  "Hawaii Warriors": "HAW",
  "Navy Midshipmen": "NAVY",
  "NC-Greensboro Spartans": "NCGS",
  "Boise State Broncos": "BSU",
  "Wisconsin-Milwaukee Panthers": "WMP",
  "Miami (Ohio) RedHawks": "M-OH",
  "Lehigh Mountain Hawks": "LEH",
  "California Baptist Lancers": "CBL",
  "Ball State Cardinals": "BALL",
  "Arkansas State Red Wolves": "ARST",
  "Rice Owls": "RICE",
  "Southern Utah Thunderbirds": "SUU",
  "Connecticut Huskies": "UCON",
  "Troy Trojans": "TROY",
  "Drexel Dragons": "DREX",
  "Maryland-Eastern Shore Hawks": "MES",
  "Eastern Kentucky Colonels": "EKY",
  "Texas State-San Marcos Bobcats": "TXST",
  "Louisiana Ragin Cajuns": "ULL",
  "Belmont Bruins": "BEL",
  "Longwood Lancers": "LONG",
  "Florida Atlantic Owls": "FAU",
  "Columbia Lions": "CLMB",
  "Mississippi State Bulldogs": "MSST",
  "TCU Horned Frogs": "TCU",
  "Temple Owls": "TEM",
  "Fresno State Bulldogs": "FRES",
  "Louisville Cardinals": "LOU",
  "Kansas Jayhawks": "KU",
  "Iona Gaels": "IONA",
  "North Alabama Lions": "NBAM",
  "Kennesaw State Owls": "KENN",
  "LIU-Brooklyn Blackbirds": "LIU",
  "Loyola-Chicago Ramblers": "LOYO",
  "Illinois-Chicago Flames": "ILCH",
  "West Virginia Mountaineers": "WVU",
  "Cal State Fullerton Titans": "CSUF",
  "Oral Roberts Golden Eagles": "ORAL",
  "Ohio State Buckeyes": "OSU",
  "Michigan State Spartans": "MSU",
  "Pittsburgh Panthers": "PITT",
  "Eastern Washington Eagles": "UWU",
  "Harvard Crimson": "HARV",
  "Mercer Bears": "MER",
  "Utah State Aggies": "UTST",
  "Tulane Green Wave": "TULN",
  "South Alabama Jaguars": "USA",
  "UAB Blazers": "UAB",
  "South Florida Bulls": "USF",
  "Nebraska Cornhuskers": "NEB",
  "Maryland-Baltimore County Retrievers": "MBC",
  "Georgetown Hoyas": "GTWN",
  "Denver Pioneers": "DEN",
  "Nebraska Omaha Mavericks": "NEBO",
  "Montana Grizzlies": "MONT",
  "Arizona Wildcats": "ARIZ",
  "Youngstown State Penguins": "YSU",
  "Portland Pilots": "PORT",
  "Texas-San Antonio Roadrunners": "TXSA",
  "Nicholls State Colonels": "NICH",
  "Yale Bulldogs": "YALE",
  "Long Beach State 49ers": "LBSU",
  "North Texas Mean Green": "UNT",
  "Toledo Rockets": "TOL",
  "South Carolina Upstate Spartans": "SCUU",
  "Tennessee Tech Golden Eagles": "TNTC",
  "Cal Poly Mustangs": "CP",
  "American Eagles": "AMER",
  "Tennessee Volunteers": "TENN",
  "Creighton Bluejays": "CREI",
  "Virginia Tech Hokies": "VT",
  "Washington State Cougars": "WSU",
  "Arkansas Razorbacks": "ARK",
  "Southern Jaguars": "SOU",
  "UCLA Bruins": "UCLA",
  "Loyola Marymount Lions": "LOMA",
  "Georgia State Panthers": "GAST",
  "Baylor Bears": "BAY",
  "UMKC Kangaroos": "UMKC",
  "Rider Broncs": "RIDE",
  "Florida Gators": "FLA",
  "Alcorn State Braves": "ACLN",
  "Mississippi Valley State Delta Devils": "MVSU",
  "Wichita State Shockers": "WICH",
  "Samford Bulldogs": "SAM",
  "Delaware Fightin' Blue Hens": "DEL",
  "UCF Knights": "UCF",
  "Utah Utes": "UTAH",
  "Idaho Vandals": "IDHO",
  "Houston Cougars": "HOU",
  "Sam Houston State Bearkats": "SHSU",
  "Texas A&M Aggies": "TAMU",
  "Georgia Tech Yellow Jackets": "GT",
  "IUPUI Jaguars": "IUPU",
  "Gardner-Webb Bulldogs": "WEBB",
  "Colgate Raiders": "COLG",
  "Wofford Terriers": "WOF",
  "Fairfield Stags": "FAIR",
  "Nevada Wolf Pack": "NEV",
  "Florida International Golden Panthers": "FIU",
  "Oregon Ducks": "ORE",
  "North Florida Ospreys": "NFU",
  "Prairie View A&M Panthers": "PV",
  "Brown Bears": "BRWN",
  "Louisiana-Monroe Warhawks": "ULM",
  "Indiana Hoosiers": "IND",
  "Fairleigh Dickinson Knights": "FADI",
  "DePaul Blue Demons": "DEPA",
  "Western Kentucky Hilltoppers": "WKU",
  "Eastern Kentucky Colonels": "EKY",
  "Central Arkansas Bears": "UCA",
  "Charleston Southern Buccaneers": "CHSO",
  "San Francisco Dons": "SFO",
  "Wisconsin Badgers": "WIS",
  "Florida A&M Rattlers": "FAMU",
  "McNeese State Cowboys": "MCNS",
  "Northern Arizona Lumberjacks": "NAU",
  "Army West Point Black Knights": "ARMY",
  "Coppin State Eagles": "COPP",
  "Brigham Young Cougars": "BYU",
  "Oklahoma State Cowboys": "OKST",
  "Lafayette Leopards": "LAF",
  "Florida Atlantic Owls": "FLAA",
  "San Jose State Spartans": "SJSU",
  "Marquette Golden Eagles": "MARQ",
  "Stetson Hatters": "STET",
  "Sacred Heart Pioneers": "SHU",
  "Howard Bison": "HOW",
  "Virginia Cavaliers": "UVA",
  "California Golden Bears": "CALU",
  "Maine Black Bears": "MAIN",
  "Winthrop Eagles": "WINT",
  "Binghamton Bearcats": "BING",
  "Long Beach State 49ers": "LBSU",
  "Cleveland State Vikings": "CLSU",
  "SIU-Edwardsville Cougars": "SIUE",
  "South Carolina State Bulldogs": "SCAR",
  "Louisiana Tech Bulldogs": "LT",
  "South Dakota State Jackrabbits": "SDSU",
  "Princeton Tigers": "PRIN",
  "South Dakota Coyotes": "SDU",
  "Texas Southern Tigers": "TXSU",
  "E. Tennessee State Buccaneers": "ETSU",
  "VMI Keydets": "VMI",
  "Cal State Fullerton Titans": "CSFU",
  "San Diego State Aztecs": "SDGS",
  "New Mexico Lobos": "UNM",
  "Northridge Matadors": "NRU",
  "Dartmouth Big Green": "DART",
  "Lipscomb Bisons": "LIPS",
  "Iowa Hawkeyes": "IOWA",
  "Northwestern Wildcats": "NW",
  "Providence Friars": "PROV",
  "North Dakota Fighting Hawks": "NDU",
  "Grambling Tigers": "GRAM",
  "Quinnipiac Bobcats": "QUIN",
  "Lamar Cardinals": "LAM",
  "Stony Brook Seawolves": "SBRU",
  "William & Mary Tribe": "W&M",
  "Stephen F. Austin Lumberjacks": "SFA",
  "New Mexico State Aggies": "NMSU",
  "Central Michigan Chippewas": "CMU",
  "Fordham Rams": "FOR",
  "Jackson State Tigers": "JKST",
  "Bowling Green Falcons": "BGSU",
  "Syracuse Orange": "SYR",
  "Georgia Southern Eagles": "GSU",
  "SMU Mustangs": "SMU",
  "Presbyterian Blue Hose": "PU",
  "Charlotte 49ers": "CU",
  "Western Illinois Leathernecks": "WIU",
  "Wyoming Cowboys": "WYO",
  "Iowa State Cyclones": "IOST",
  "Rutgers Scarlet Knights": "RUTG",
  "Air Force Falcons": "AFA",
  "Loyola-Maryland Greyhounds": "LOMD",
  "Robert Morris Colonials": "RMU",
  "Duke Blue Devils": "DUKE",

  "Seton Hall Pirates": "SETH",
  "Utah Valley Wolverines": "UTVL",
  "Texas-El Paso Miners": "UTEP",
  "Kent State Golden Flashes": "KENT",
  "Maryland Terrapins": "UMD",
  "Gonzaga Bulldogs": "GONZ",
  "Texas-Arlington Mavericks": "TARL",
  "UC Davis Aggies": "UCD",
  "Indiana State Sycamores": "INST",
  "Butler Bulldogs": "BUT",
  "Clemson Tigers": "CLEM",
  "Bethune-Cookman Wildcats": "COOK",
  "Pacific Tigers": "PACT",
  "Michigan Wolverines": "MICH",
  "Kentucky Wildcats": "UK",
  "Boston College Eagles": "BC",
  "UNC-Asheville Bulldogs": "UNCA",
  "Morehead State Eagles": "MORE",
  "Jacksonville Dolphins": "JAC",
  "Massachusetts Minutemen": "UMAS",
  "Incarnate Word Cardinals": "IW",
  "Pepperdine Waves": "PEPP",
  "Eastern Michigan Eagles": "EMCH",
  "Coastal Carolina Chanticleers": "CCU",
  "UNLV Rebels": "UNLV",
  "Akron Zips": "AKR",
  "James Madison Dukes": "JMU",
  "Arkansas-Pine Bluff Golden Lions": "APRB",
  "Little Rock Trojans": "LRU",
  "Colorado State Rams": "CSU",
  "Bradley Braves": "BRAD",
  "Liberty Flames": "LIB",
  "Cal State Bakersfield Roadrunners": "CSBK",
  "Mount St. Mary's Mountaineers": "MSTM",
  "Boston University Terriers": "BU",
  "Oregon State Beavers": "ORST",
  "Weber State Wildcats": "WEB",
  "Hampton Pirates": "HAMP",
  "Alabama Crimson Tide": "BAMA",
  "San Diego Toreros": "USD",
  "Cincinnati Bearcats": "CIN",
  "Southern Illinois Salukis": "SIU",
  "Niagara Purple Eagles": "NIAG",
  "Wright State Raiders": "WRIG",
  "NC State Wolfpack": "NCSU",
  "Central Connecticut State Blue Devils": "CCSU",
  "Colorado Buffaloes": "COL",
  "App. State Mountaineers": "APP",
  "Delaware State Hornets": "DST",
  "Florida Gulf Coast Eagles": "FGCU",
  "La Salle Explorers": "ULS",
  "Oakland Golden Grizzlies": "UOAK",
  "Evansville Aces": "EVAN",
  "St. Francis (N.Y.) Terriers": "STFR",
  "Morgan State Bears": "MORG",
  "Chicago State Cougars": "CHIS",
  "Green Bay Phoenix": "GBPX",
  "New Jersey Tech Highlanders": "NJT",
  "Purdue Fort Wayne Mastodons": "PFW",
  "UMass Lowell River Hawks": "UMLU",
  "Marshall Thundering Herd": "MRSH",
  "Texas Tech Red Raiders": "TTU",
  "Holy Cross Crusaders": "HC",
  "Northern Colorado Bears": "UNCO",
  "Northern Iowa Panthers": "UNIO",
  "High Point Panthers": "HP",
  "Buffalo Bulls": "BUF",
  "New Orleans Privateers": "UNO",
  "Stanford Cardinal": "STAN",
  "Saint Louis Billikens": "STL",
  "Pennsylvania Quakers": "PENN",
  "Towson Tigers": "TOWS",
  "Villanova Wildcats": "NOVA",
  "Illinois Fighting Illini": "ILL",
  "Oklahoma Sooners": "OU",
  "LSU Tigers": "LSU",
  "Wake Forest Demon Deacons": "WAKE",
  "Northwestern State Demons": "NWST",
  "Norfolk State Spartans": "NORF",
  "Duquesne Dukes": "DUQ",
  "Detroit Titans": "DET",
  "North Carolina Tar Heels": "UNC",
  "College of Charleston Cougars": "CCHA",
  "St. Francis (Pa.) Red Flash": "SFU",
  "Santa Barbara Gauchos": "SBU",
  "Auburn Tigers": "AUB",
  "Hartford Hawks": "HART",
  "Montana State Bobcats": "MNST",
  "Ohio Bobcats": "OHIO",
  "Grand Canyon Antelopes": "GRCA",
  "Davidson Wildcats": "DAV",
  "Cornell Big Red": "COR",
  "UT Martin Skyhawks": "UTMA",
  "South Carolina Gamecocks": "SC",
  "Penn State Nittany Lions": "PSU",
  "Houston Baptist Huskies": "HOUB",
  "Southeastern Louisiana Lions": "SELA",
  "St. Peter's Peacocks": "STPT",
  "Furman Paladins": "FURM",
  "Xavier Musketeers": "XAV",
  "Northeastern Huskies": "NE",
  "Texas-Rio Grande Valley Vaqueros": "TRGV",
  "Manhattan Jaspers": "MAN",
  "Memphis Tigers": "MEM",
  "Idaho State Bengals": "IDST",
  "Illinois State Redbirds": "ILST",
  "George Mason Patriots": "GEMA",
  "Western Michigan Broncos": "WMU",
  "Valparaiso Crusaders": "VALP",
  "Northern Illinois Huskies": "NIU",
  "New Hampshire Wildcats": "UNH",
  "Missouri Tigers": "MIZZ",
  "Southeast Missouri State Redhawks": "SEMI",
  "Sacramento State Hornets": "SAC",
  "Old Dominion Monarchs": "ODU",
  "Albany Great Danes": "ALBY",
  "Kansas State Wildcats": "KSU",
  "Saint Joseph's Hawks": "SJOE",
  "Vanderbilt Commodores": "VAN",
  "Portland State Vikings": "PRST",
  "Eastern Illinois Panthers": "EIU",
  "The Citadel Bulldogs": "CIT",
  "UNC-Wilmington Seahawks": "UNCW",
  "Chattanooga Mocs": "CHAT",
  "Texas A&M-Corpus Christi Islanders": "TCCH",
  "George Washington Colonials": "GWAS",
  "Missouri State Bears": "MZST",
  "Seattle Redhawks": "SEA",
  "Murray State Racers": "MUST",
  "Savannah State Tigers": "SVST",
  "Ole Miss Rebels": "MISS",
  "Hofstra Pride": "HOF",
  "Jacksonville State Gamecocks": "JVST",
  "Alabama A&M Bulldogs": "AAMU",
  "Campbell Fighting Camels": "CAMP",
  "Notre Dame Fighting Irish": "ND",
  "Middle Tennessee Blue Raiders": "MTSU",
  "UC Irvine Anteaters": "UCIR",
  "Radford Highlanders": "RAD",
  "VCU Rams": "VCU",
  "Georgia Bulldogs": "UGA",
  "Bucknell Bison": "BUCK",
  "East Carolina Pirates": "UEC",
  "Richmond Spiders": "RICH",
  "St. Bonaventure Bonnies": "BONV",
  "Western Carolina Catamounts": "WCU",
  "Minnesota Golden Gophers": "MINN",
  "Florida State Seminoles": "FSU",
  "Texas Longhorns": "TEX",
  "Elon Phoenix": "ELON",
  "Monmouth Hawks": "MONM",
  "Marist Red Foxes": "MRST",
  "Dayton Flyers": "DAY",
  "Vermont Catamounts": "VERM",
  "Drake Bulldogs": "DRKE",
  "North Carolina Central Eagles": "NCC",
  "Saint Mary's Gaels": "STMY",
  "Alabama State Hornets": "ALST",
  "California Riverside Highlanders": "CARI",
  "Siena Saints": "SIEN",
  "Arizona State Sun Devils": "ASU",
  "Abilene Christian Wildcats": "ACU",
  "Wagner Seahawks": "WAG",
  "St. John's Red Storm": "STJO",
  "Rhode Island Rams": "URI",
  "Miami (Fla.) Hurricanes": "MIA",
  "Tulsa Golden Hurricane": "TLSA",
  "Northern Kentucky Norse": "NKEN",
  "Canisius Golden Griffins": "CANI",
  "Bryant University Bulldogs": "BRY",
  "Southern Miss Golden Eagles": "USM",
  "Santa Clara Broncos": "SCLR",
  "North Carolina A&T Aggies": "NCAT",
  "Tennessee State Tigers": "TNST",
  "North Dakota State Bison": "UND",
  "Purdue Boilermakers": "PUR",
  "St. Bona. Bonnies": "BONA",
  "Middle Tenn. Blue Raiders": "MTEN",
  "N. Mex. St. Aggies": "NMEX",
  "Texas So. Tigers": "TXSO",
  "Washington Huskies": "WAS",
};

module.exports = ncaabbTeams;
