const nflTeams = {
  "Arizona Cardinals": "ARI",
  "Atlanta Falcons": "ATL",
  "Baltimore Ravens": "BAL",
  "Buffalo Bills": "BUF",
  "Carolina Panthers": "CAR",
  "Chicago Bears": "CHI",
  "Cincinnati Bengals": "CIN",
  "Cleveland Browns": "CLE",
  "Dallas Cowboys": "DAL",
  "Denver Broncos": "DEN",
  "Detroit Lions": "DET",
  "Green Bay Packers": "GNB",
  "Houston Texans": "HOU",
  "Indianapolis Colts": "IND",
  "Jacksonville Jaguars": "JAC",
  "Kansas City Chiefs": "K.C",
  "Los Angeles Chargers": "LAC",
  "Los Angeles Rams": "LAR",
  "Miami Dolphins": "MIA",
  "Minnesota Vikings": "MIN",
  "New England Patriots": "NWE",
  "New Orleans Saints": "NOR",
  "New York Giants": "NYG",
  "New York Jets": "NYJ",
  "Oakland Raiders": "OAK",
  "Philadelphia Eagles": "PHI",
  "Pittsburgh Steelers": "PIT",
  "San Francisco 49ers": "SFO",
  "Seattle Seahawks": "SEA",
  "Tampa Bay Buccaneers": "TAM",
  "Tennessee Titans": "TEN",
  "Washington Redskins": "WAS"
};

const nflTeamNames = {
  "ARI": "Cardinals, Arizona",
  "ATL": "Falcons, Atlanta",
  "BAL": "Ravens, Baltimore",
  "BUF": "Bills, Buffalo",
  "CAR": "Panthers, Carolina",
  "CHI": "Bears, Chicago",
  "CIN": "Bengals, Cincinnati",
  "CLE": "Browns, Cleveland",
  "DAL": "Cowboys, Dallas",
  "DEN": "Broncos, Denver",
  "DET": "Lions, Detroit",
  "GNB": "Packers, Green Bay",
  "HOU": "Texans, Houston",
  "IND": "Colts, Indianapolis",
  "JAC": "Jaguars, Jacksonville",
  "K.C": "Chiefs, Kansas City",
  "LAC": "Chargers, Los Angeles",
  "LAR": "Rams, Los Angeles",
  "MIA": "Dolphins, Miami",
  "MIN": "Vikings, Minnesota",
  "NWE": "Patriots, New England",
  "NOR": "Saints, New Orleans",
  "NYG": "Giants, New York",
  "NYJ": "Jets, New York",
  "OAK": "Raiders, Oakland",
  "PHI": "Eagles, Philadelphia",
  "PIT": "Steelers, Pittsburgh",
  "SFO": "49ers, San Francisco",
  "SEA": "Seahawks, Seattle",
  "TAM": "Buccaneers, Tampa Bay",
  "TEN": "Titans, Tennessee",
  "WAS": "Redskins, Washington"
};

module.exports = { nflTeams, nflTeamNames };
