const ncaafbTeams = {
    "Cincinnati Bearcats": "CINCY",
    "East Carolina Pirates": "ECU",
    "Houston Cougars": "HOU",
    "Memphis Tigers": "MEMP",
    "Navy Midshipmen": "NAVY",
    "SMU Mustangs": "SMU",
    "South Florida Bulls": "SFLA",
    "Temple Owls": "TEMPLE",
    "Tulane Green Wave": "TULANE",
    "Tulsa Golden Hurricane": "TULSA",
    "UCF Knights": "UCF",
    "Boston College Eagles": "BC",
    "Clemson Tigers": "CLEM",
    "Florida State Seminoles": "FSU",
    "Louisville Cardinals": "LVILLE",
    "NC State Wolfpack": "NCST",
    "Syracuse Orange": "CUSE",
    "Wake Forest Demon Deacons": "WAKE",
    "Duke Blue Devils": "DUKE",
    "Georgia Tech Yellow Jackets": "GATECH",
    "Miami (FL) Hurricanes": "MIAMI",
    "North Carolina Tar Heels": "UNC",
    "Pittsburgh Panthers": "PITT",
    "Virginia Cavaliers": "UVA",
    "Virginia Tech Hokies": "VATECH",
    "Indiana Hoosiers": "IND",
    "Maryland Terrapins": "MD",
    "Michigan Wolverines": "MICH",
    "Michigan State Spartans": "MICHST",
    "Ohio State Buckeyes": "OHIOST",
    "Penn State Nittany Lions": "PSU",
    "Rutgers Scarlet Knights": "RUT",
    "Illinois Fighting Illini": "ILL",
    "Iowa Hawkeyes": "IOWA",
    "Minnesota Golden Gophers": "MINN",
    "Nebraska Cornhuskers": "NEB",
    "Northwestern Wildcats": "NWEST",
    "Purdue Boilermakers": "PURDUE",
    "Wisconsin Badgers": "WISC",
    "Baylor Bears": "BAYLOR",
    "Iowa State Cyclones": "IOWAST",
    "Kansas Jayhawks": "KANSAS",
    "Kansas State Wildcats": "KSTATE",
    "Oklahoma State Cowboys": "OKLAST",
    "Oklahoma Sooners": "OKLA",
    "TCU Horned Frogs": "TCU",
    "Texas Longhorns": "TEXAS",
    "Texas Tech Red Raiders": "TXTECH",
    "West Virginia Mountaineers": "WVU",
    "Charlotte 49ers": "CHARLO",
    "Florida Atlantic Owls": "FAU",
    "FIU Panthers": "FIU",
    "Marshall Thundering Herd": "MRSHL",
    "Middle Tenn. Blue Raiders": "MTSU",
    "Old Dominion Monarchs": "ODU",
    "Western Kentucky Hilltoppers": "WKY",
    "Louisiana Tech Bulldogs": "LATECH",
    "North Texas Mean Green": "NTEXAS",
    "Rice Owls": "RICE",
    "Southern Miss Golden Eagles": "USM",
    "UAB Blazers": "UAB",
    "UTEP Miners": "UTEP",
    "UTSA Roadrunners": "TXSA",
    "Army West Point Black Knights": "ARMY",
    "BYU Cougars": "BYU",
    "Liberty Flames": "LIB",
    "New Mexico State Aggies": "NMEXST",
    "Notre Dame Fighting Irish": "ND",
    "Connecticut Huskies": "UCONN",
    "Massachusetts Minutemen": "UMASS",
    "Akron Zips": "AKRON",
    "Bowling Green Falcons": "BGREEN",
    "Buffalo Bulls": "BUFF",
    "Kent State Golden Flashes": "KENTST",
    "Miami (OH) RedHawks": "MIAOH",
    "Ohio Bobcats": "OHIO",
    "Ball State Cardinals": "BALLST",
    "Central Michigan Chippewas": "CMICH",
    "Eastern Michigan Eagles": "EMICH",
    "Northern Illinois Huskies": "NILL",
    "Toledo Rockets": "TOLEDO",
    "Western Michigan Broncos": "WMICH",
    "Air Force Falcons": "AF",
    "Boise State Broncos": "BOISE",
    "Colorado State Rams": "COLOST",
    "New Mexico Lobos": "NMEX",
    "Utah State Aggies": "UTAHST",
    "Wyoming Cowboys": "WYO",
    "Fresno State Bulldogs": "FRESNO",
    "Hawaii Rainbow Warriors": "HAWAII",
    "Nevada Wolf Pack": "NEVADA",
    "San Diego State Aztecs": "SDGST",
    "San Jose State Spartans": "SJST",
    "UNLV Rebels": "UNLV",
    "California Golden Bears": "CAL",
    "Oregon Ducks": "OREG",
    "Oregon State Beavers": "OREGST",
    "Stanford Cardinal": "STNFRD",
    "Washington Huskies": "WASH",
    "Washington State Cougars": "WASHST",
    "Arizona Wildcats": "ARIZ",
    "Arizona State Sun Devils": "ARIZST",
    "Colorado Buffaloes": "COLO",
    "UCLA Bruins": "UCLA",
    "USC Trojans": "USC",
    "Utah Utes": "UTAH",
    "Florida Gators": "FLA",
    "Georgia Bulldogs": "UGA",
    "Kentucky Wildcats": "UK",
    "Missouri Tigers": "MIZZOU",
    "South Carolina Gamecocks": "SC",
    "Tennessee Volunteers": "TENN",
    "Vanderbilt Commodores": "VANDY",
    "Alabama Crimson Tide": "BAMA",
    "Arkansas Razorbacks": "ARK",
    "Auburn Tigers": "AUBURN",
    "LSU Tigers": "LSU",
    "Mississippi State Bulldogs": "MISSST",
    "Ole Miss Rebels": "MISS",
    "Texas A&M Aggies": "TXAM",
    "Appalachian State Mountaineers": "APLST",
    "Coastal Carolina Chanticleers": "CSTCAR",
    "Georgia Southern Eagles": "GAS",
    "Georgia State Panthers": "GAST",
    "James Madison Dukes": "JMAD",
    "Troy Trojans": "TROY",
    "Arkansas State Red Wolves": "ARKST",
    "Louisiana Ragin' Cajuns": "UL",
    "South Alabama Jaguars": "SALA",
    "Texas State Bobcats": "TXSTSM",
    "Louisiana-Monroe Warhawks": "LAMON"
};

const ncaaFbTeamUrlAbbreviations = {};

export {ncaafbTeams, ncaaFbTeamUrlAbbreviations};